name: .NET

on:
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
      with:
        ref: emby
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - run: |
        sudo apt update
        sudo apt install libkrb5-dev liblttng-ust-dev -y
        sudo apt-get install -y cmake llvm-9 clang-9 build-essential python curl git lldb-6.0 liblldb-6.0-dev libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libssl-dev libnuma-dev libkrb5-dev zlib1g-dev ninja-build
    - run: |
        sudo ./build.sh -subset clr
    - name: Start SSH via tmate
      uses: rdp-studio/ssh2actions@main
      # Send connection info to Telegram (optional)
      # You can find related documents here: https://core.telegram.org/bots
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    - run: |
        sudo ./build.sh libs --configuration Release --os Linux --arch arm64 -lc Release -rc Release -cross
    - name : Upload artifact
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: artifacts
        path: artifacts/bin/System.Net.Http/
